service: serverless-cloudwatch

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  Resources:
## CloudWatch custom metrics
    ServerlessCloudWatchCustomMetricFilter:
      Type: "AWS::Logs::MetricFilter"
      Properties:
        LogGroupName: /aws/lambda/serverless-cloudwatch-dev-hello
        FilterPattern: "RECORD HI"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: CustomMetric
            MetricName: hello-metric-dev
